[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# ASYNC and HTTP
axum = {version = "0.8", features=["ws"]}
axum-extra = { version = "0.10", features = ["multipart", "typed-header", "cookie", "query", "file-stream"] }
tokio = { version = "1.47", features=["full"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "uuid", "time"]}
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors", "request-id", "fs"] }
futures = "0.3"

# SERIALIZER
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"

# FFI
# cxx = "1.0"
libloading = "0.8"

# LOGGING
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# ERRORS
thiserror = "2"
anyhow = "1"

# AUTH
time = { version = "0.3", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
jsonwebtoken = "9"
argon2 = "0.5"
password-hash = "0.5"
rand = "0.8"

bytes = "1"

[build-dependencies]
# cxx-build = "1.0"
